export const dogBreeds: { [key: string]: string } = {
  affenpinscher: 'Affenpinscher',
  afghanHound: 'Lebrel Afgano',
  airedaleTerrier: 'Airedale Terrier',
  akita: 'Akita',
  alaskanMalamute: 'Alaskan Malamute',
  americanEskimoDog: 'Perro Esquimal Americano',
  americanFoxhound: 'Foxhound Americano',
  americanStaffordshireTerrier: 'Staffordshire Terrier Americano',
  australianCattleDog: 'Boyero Australiano',
  australianShepherd: 'Pastor Australiano',
  australianTerrier: 'Terrier Australiano',
  basenji: 'Basenji',
  bassetHound: 'Basset Hound',
  beagle: 'Beagle',
  beardedCollie: 'Collie Barbudo',
  bedlingtonTerrier: 'Bedlington Terrier',
  belgianMalinois: 'Pastor Belga Malinois',
  belgianSheepdog: 'Pastor Belga',
  belgianTervuren: 'Pastor Belga Tervuren',
  berneseMountainDog: 'Boyero de Berna',
  bichonFrise: 'Bichón Frisé',
  blackAndTanCoonhound: 'Coonhound Negro y Fuego',
  bloodhound: 'Sabueso',
  borderCollie: 'Border Collie',
  borderTerrier: 'Border Terrier',
  borzoi: 'Borzoi',
  bostonTerrier: 'Boston Terrier',
  bouvierDesFlandres: 'Bouvier de Flandes',
  boxer: 'Boxer',
  briard: 'Briard',
  brittany: 'Braco de Bretaña',
  brusselsGriffon: 'Grifón de Bruselas',
  bullTerrier: 'Bull Terrier',
  bulldog: 'Bulldog',
  bullmastiff: 'Bullmastiff',
  cairnTerrier: 'Cairn Terrier',
  canaanDog: 'Perro de Canaán',
  caneCorso: 'Cane Corso',
  cardiganWelshCorgi: 'Corgi Galés de Cardigan',
  cavalierKingCharlesSpaniel: 'Cavalier King Charles Spaniel',
  chesapeakeBayRetriever: 'Retriever de la Bahía de Chesapeake',
  chihuahua: 'Chihuahua',
  chineseCrested: 'Crestado Chino',
  chowChow: 'Chow Chow',
  clumberSpaniel: 'Clumber Spaniel',
  cockapoo: 'Cockapoo',
  cockerSpaniel: 'Cocker Spaniel',
  collie: 'Collie',
  coonhound: 'Coonhound',
  corgi: 'Corgi',
  cotonDeTulear: 'Coton de Tuléar',
  dachshund: 'Dachshund (Perro Salchicha)',
  dalmatian: 'Dálmata',
  dandieDinmontTerrier: 'Dandie Dinmont Terrier',
  dobermanPinscher: 'Doberman',
  dogoArgentino: 'Dogo Argentino',
  englishBulldog: 'Bulldog Inglés',
  englishSetter: 'Setter Inglés',
  englishSpringerSpaniel: 'Springer Spaniel Inglés',
  englishToySpaniel: 'Spaniel Inglés de Juguete',
  eskimoDog: 'Perro Esquimal',
  fieldSpaniel: 'Field Spaniel',
  finnishSpitz: 'Spitz Finlandés',
  flatCoatedRetriever: 'Retriever de Pelo Liso',
  foxTerrier: 'Fox Terrier',
  frenchBulldog: 'Bulldog Francés',
  germanPinscher: 'Pinscher Alemán',
  germanShepherd: 'Pastor Alemán',
  germanShorthairedPointer: 'Braco Alemán de Pelo Corto',
  giantSchnauzer: 'Schnauzer Gigante',
  smallMixed: 'Mestizo Pequeño',
  mediumMixed: 'Mestizo Mediano',
  largeMixed: 'Mestizo Grande',
  undefinedMixed: 'Mestizo Tamaño Desconocido',
};

export const dogBreedSelectableOptions = [
  { value: 'affenpinscher', label: 'Affenpinscher' },
  { value: 'afghanHound', label: 'Lebrel Afgano' },
  { value: 'airedaleTerrier', label: 'Airedale Terrier' },
  { value: 'akita', label: 'Akita' },
  { value: 'alaskanMalamute', label: 'Alaskan Malamute' },
  { value: 'americanEskimoDog', label: 'Perro Esquimal Americano' },
  { value: 'americanFoxhound', label: 'Foxhound Americano' },
  {
    value: 'americanStaffordshireTerrier',
    label: 'Staffordshire Terrier Americano',
  },
  { value: 'australianCattleDog', label: 'Boyero Australiano' },
  { value: 'australianShepherd', label: 'Pastor Australiano' },
  { value: 'australianTerrier', label: 'Terrier Australiano' },
  { value: 'basenji', label: 'Basenji' },
  { value: 'bassetHound', label: 'Basset Hound' },
  { value: 'beagle', label: 'Beagle' },
  { value: 'beardedCollie', label: 'Collie Barbudo' },
  { value: 'bedlingtonTerrier', label: 'Bedlington Terrier' },
  { value: 'belgianMalinois', label: 'Pastor Belga Malinois' },
  { value: 'belgianSheepdog', label: 'Pastor Belga' },
  { value: 'belgianTervuren', label: 'Pastor Belga Tervuren' },
  { value: 'berneseMountainDog', label: 'Boyero de Berna' },
  { value: 'bichonFrise', label: 'Bichón Frisé' },
  { value: 'blackAndTanCoonhound', label: 'Coonhound Negro y Fuego' },
  { value: 'bloodhound', label: 'Sabueso' },
  { value: 'borderCollie', label: 'Border Collie' },
  { value: 'borderTerrier', label: 'Border Terrier' },
  { value: 'borzoi', label: 'Borzoi' },
  { value: 'bostonTerrier', label: 'Boston Terrier' },
  { value: 'bouvierDesFlandres', label: 'Bouvier de Flandes' },
  { value: 'boxer', label: 'Boxer' },
  { value: 'briard', label: 'Briard' },
  { value: 'brittany', label: 'Braco de Bretaña' },
  { value: 'brusselsGriffon', label: 'Grifón de Bruselas' },
  { value: 'bullTerrier', label: 'Bull Terrier' },
  { value: 'bulldog', label: 'Bulldog' },
  { value: 'bullmastiff', label: 'Bullmastiff' },
  { value: 'cairnTerrier', label: 'Cairn Terrier' },
  { value: 'canaanDog', label: 'Perro de Canaán' },
  { value: 'caneCorso', label: 'Cane Corso' },
  { value: 'cardiganWelshCorgi', label: 'Corgi Galés de Cardigan' },
  {
    value: 'cavalierKingCharlesSpaniel',
    label: 'Cavalier King Charles Spaniel',
  },
  {
    value: 'chesapeakeBayRetriever',
    label: 'Retriever de la Bahía de Chesapeake',
  },
  { value: 'chihuahua', label: 'Chihuahua' },
  { value: 'chineseCrested', label: 'Crestado Chino' },
  { value: 'chowChow', label: 'Chow Chow' },
  { value: 'clumberSpaniel', label: 'Clumber Spaniel' },
  { value: 'cockapoo', label: 'Cockapoo' },
  { value: 'cockerSpaniel', label: 'Cocker Spaniel' },
  { value: 'collie', label: 'Collie' },
  { value: 'coonhound', label: 'Coonhound' },
  { value: 'corgi', label: 'Corgi' },
  { value: 'cotonDeTulear', label: 'Coton de Tuléar' },
  { value: 'dachshund', label: 'Dachshund (Perro Salchicha)' },
  { value: 'dalmatian', label: 'Dálmata' },
  { value: 'dandieDinmontTerrier', label: 'Dandie Dinmont Terrier' },
  { value: 'dobermanPinscher', label: 'Doberman' },
  { value: 'dogoArgentino', label: 'Dogo Argentino' },
  { value: 'englishBulldog', label: 'Bulldog Inglés' },
  { value: 'englishSetter', label: 'Setter Inglés' },
  { value: 'englishSpringerSpaniel', label: 'Springer Spaniel Inglés' },
  { value: 'englishToySpaniel', label: 'Spaniel Inglés de Juguete' },
  { value: 'eskimoDog', label: 'Perro Esquimal' },
  { value: 'fieldSpaniel', label: 'Field Spaniel' },
  { value: 'finnishSpitz', label: 'Spitz Finlandés' },
  { value: 'flatCoatedRetriever', label: 'Retriever de Pelo Liso' },
  { value: 'foxTerrier', label: 'Fox Terrier' },
  { value: 'frenchBulldog', label: 'Bulldog Francés' },
  { value: 'germanPinscher', label: 'Pinscher Alemán' },
  { value: 'germanShepherd', label: 'Pastor Alemán' },
  { value: 'germanShorthairedPointer', label: 'Braco Alemán de Pelo Corto' },
  { value: 'giantSchnauzer', label: 'Schnauzer Gigante' },
  { value: 'smallMixed', label: 'Mestizo Pequeño' },
  { value: 'mediumMixed', label: 'Mestizo Mediano' },
  { value: 'largeMixed', label: 'Mestizo Grande' },
  { value: 'undefinedMixed', label: 'Mestizo Tamaño Desconocido' },
];
